/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package EposSimple.Dialogs;

import EposSimple.EposSimpleApp;
import EposSimple.Models.Product;
import EposSimple.Models.SoldProduct;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JDialog;

/**
 *
 * @author tg
 */
public class ProductEditDialog extends JDialog {

    private final ArrayList<JButton> amountButtons;
    private final SoldProduct product;
    private final EposSimpleApp parentFrame;
    private final ImageIcon iconSelected = new ImageIcon(getClass().getResource("/Images/icons8-filled-circle-60.png"));
    private final ImageIcon iconUnselected = new ImageIcon(getClass().getResource("/Images/icons8-circle-60.png"));

    /**
     * Creates new form ProductAmount
     *
     * @param parentFrame
     * @param product
     */
    public ProductEditDialog(EposSimpleApp parentFrame, SoldProduct product) {
        this.product = product;
        this.parentFrame = parentFrame;
        amountButtons = new ArrayList<>();
        
        initComponents();
        
        setLocationRelativeTo(null);
        getRootPane().setBorder(BorderFactory.createMatteBorder(2, 2, 2, 2, Color.BLACK));
                
        amountButtons.add(0, btnAmount1);
        amountButtons.add(1, btnAmount2);
        amountButtons.add(2, btnAmount3);
        amountButtons.add(3, btnAmount4);
        amountButtons.add(4, btnAmount5);
        
        for(int i = 0; i < amountButtons.size(); i++){
            int buttonValue = Integer.valueOf(amountButtons.get(i).getText());
            if(buttonValue == product.getAmountSold()){
                amountButtons.get(i).setIcon(iconSelected);
            }
        }

        lblProductImage.setIcon(product.getProductIcon(65, 65));
        lblProductName.setText(product.getName());
        lblProductPrice.setText("[ £" + product.getPrice() + " ]");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        pnlTopPanel = new javax.swing.JPanel();
        lblProductImage = new javax.swing.JLabel();
        lblProductName = new javax.swing.JLabel();
        lblProductPrice = new javax.swing.JLabel();
        pnlBottomPanel = new javax.swing.JPanel();
        lblSelectAmount = new javax.swing.JLabel();
        pnlSelectAmount = new javax.swing.JPanel();
        btnDecreseRange = new javax.swing.JButton();
        btnAmount1 = new javax.swing.JButton();
        btnAmount2 = new javax.swing.JButton();
        btnAmount3 = new javax.swing.JButton();
        btnAmount4 = new javax.swing.JButton();
        btnAmount5 = new javax.swing.JButton();
        btnIncreaseRange = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setForeground(java.awt.Color.white);
        setMinimumSize(new java.awt.Dimension(622, 265));
        setUndecorated(true);
        setResizable(false);
        setType(java.awt.Window.Type.UTILITY);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        pnlTopPanel.setBackground(new java.awt.Color(255, 255, 255));
        pnlTopPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        pnlTopPanel.setAlignmentX(0.0F);
        pnlTopPanel.setAlignmentY(0.0F);
        pnlTopPanel.setLayout(new javax.swing.BoxLayout(pnlTopPanel, javax.swing.BoxLayout.LINE_AXIS));

        lblProductImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ProductImages/bread.png"))); // NOI18N
        lblProductImage.setMaximumSize(new java.awt.Dimension(80, 80));
        lblProductImage.setMinimumSize(new java.awt.Dimension(80, 80));
        lblProductImage.setPreferredSize(new java.awt.Dimension(80, 80));
        pnlTopPanel.add(lblProductImage);

        lblProductName.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblProductName.setText("Product Name");
        lblProductName.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 5, 1, 1));
        pnlTopPanel.add(lblProductName);

        lblProductPrice.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblProductPrice.setText("£3.44");
        lblProductPrice.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1));
        pnlTopPanel.add(lblProductPrice);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        getContentPane().add(pnlTopPanel, gridBagConstraints);

        pnlBottomPanel.setBackground(new java.awt.Color(255, 255, 255));
        pnlBottomPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 1, 20, 1));
        pnlBottomPanel.setLayout(new javax.swing.BoxLayout(pnlBottomPanel, javax.swing.BoxLayout.PAGE_AXIS));

        lblSelectAmount.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblSelectAmount.setText("Select Amount:");
        lblSelectAmount.setAlignmentX(0.5F);
        pnlBottomPanel.add(lblSelectAmount);

        pnlSelectAmount.setBackground(new java.awt.Color(255, 255, 255));
        pnlSelectAmount.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));

        btnDecreseRange.setBackground(new java.awt.Color(255, 255, 255));
        btnDecreseRange.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        btnDecreseRange.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-circle-60.png"))); // NOI18N
        btnDecreseRange.setText("<");
        btnDecreseRange.setBorderPainted(false);
        btnDecreseRange.setEnabled(false);
        btnDecreseRange.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnDecreseRange.setMaximumSize(new java.awt.Dimension(80, 80));
        btnDecreseRange.setMinimumSize(new java.awt.Dimension(80, 80));
        btnDecreseRange.setPreferredSize(new java.awt.Dimension(80, 80));
        btnDecreseRange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDecreseRangeActionPerformed(evt);
            }
        });
        pnlSelectAmount.add(btnDecreseRange);

        btnAmount1.setBackground(new java.awt.Color(255, 255, 255));
        btnAmount1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnAmount1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-circle-60.png"))); // NOI18N
        btnAmount1.setText("1");
        btnAmount1.setBorderPainted(false);
        btnAmount1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAmount1.setMaximumSize(new java.awt.Dimension(80, 80));
        btnAmount1.setMinimumSize(new java.awt.Dimension(80, 80));
        btnAmount1.setPreferredSize(new java.awt.Dimension(80, 80));
        btnAmount1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAmountActionPerformed(evt);
            }
        });
        pnlSelectAmount.add(btnAmount1);

        btnAmount2.setBackground(new java.awt.Color(255, 255, 255));
        btnAmount2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnAmount2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-circle-60.png"))); // NOI18N
        btnAmount2.setText("2");
        btnAmount2.setBorderPainted(false);
        btnAmount2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAmount2.setMaximumSize(new java.awt.Dimension(80, 80));
        btnAmount2.setMinimumSize(new java.awt.Dimension(80, 80));
        btnAmount2.setPreferredSize(new java.awt.Dimension(80, 80));
        btnAmount2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAmountActionPerformed(evt);
            }
        });
        pnlSelectAmount.add(btnAmount2);

        btnAmount3.setBackground(new java.awt.Color(255, 255, 255));
        btnAmount3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnAmount3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-circle-60.png"))); // NOI18N
        btnAmount3.setText("3");
        btnAmount3.setBorderPainted(false);
        btnAmount3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAmount3.setMaximumSize(new java.awt.Dimension(80, 80));
        btnAmount3.setMinimumSize(new java.awt.Dimension(80, 80));
        btnAmount3.setPreferredSize(new java.awt.Dimension(80, 80));
        btnAmount3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAmountActionPerformed(evt);
            }
        });
        pnlSelectAmount.add(btnAmount3);

        btnAmount4.setBackground(new java.awt.Color(255, 255, 255));
        btnAmount4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnAmount4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-circle-60.png"))); // NOI18N
        btnAmount4.setText("4");
        btnAmount4.setBorderPainted(false);
        btnAmount4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAmount4.setMaximumSize(new java.awt.Dimension(80, 80));
        btnAmount4.setMinimumSize(new java.awt.Dimension(80, 80));
        btnAmount4.setPreferredSize(new java.awt.Dimension(80, 80));
        btnAmount4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAmountActionPerformed(evt);
            }
        });
        pnlSelectAmount.add(btnAmount4);

        btnAmount5.setBackground(new java.awt.Color(255, 255, 255));
        btnAmount5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnAmount5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-circle-60.png"))); // NOI18N
        btnAmount5.setText("5");
        btnAmount5.setBorderPainted(false);
        btnAmount5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAmount5.setMaximumSize(new java.awt.Dimension(80, 80));
        btnAmount5.setMinimumSize(new java.awt.Dimension(80, 80));
        btnAmount5.setPreferredSize(new java.awt.Dimension(80, 80));
        btnAmount5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAmountActionPerformed(evt);
            }
        });
        pnlSelectAmount.add(btnAmount5);

        btnIncreaseRange.setBackground(new java.awt.Color(255, 255, 255));
        btnIncreaseRange.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        btnIncreaseRange.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-circle-60.png"))); // NOI18N
        btnIncreaseRange.setText(">");
        btnIncreaseRange.setBorderPainted(false);
        btnIncreaseRange.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnIncreaseRange.setMaximumSize(new java.awt.Dimension(80, 80));
        btnIncreaseRange.setMinimumSize(new java.awt.Dimension(80, 80));
        btnIncreaseRange.setPreferredSize(new java.awt.Dimension(80, 80));
        btnIncreaseRange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIncreaseRangeActionPerformed(evt);
            }
        });
        pnlSelectAmount.add(btnIncreaseRange);

        pnlBottomPanel.add(pnlSelectAmount);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        getContentPane().add(pnlBottomPanel, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDecreseRangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDecreseRangeActionPerformed
        for (int i = 0; i < amountButtons.size(); i++) {
            int buttonValue = Integer.valueOf(amountButtons.get(i).getText());
            buttonValue = buttonValue - amountButtons.size();
            amountButtons.get(i).setText(String.valueOf(buttonValue));
            
            if(buttonValue == product.getAmountSold()){
                amountButtons.get(i).setIcon(iconSelected);
            }else{
                amountButtons.get(i).setIcon(iconUnselected);
            }
        }
        if (amountButtons.get(0).getText().equals("1")) {
            btnDecreseRange.setEnabled(false);
        }
    }//GEN-LAST:event_btnDecreseRangeActionPerformed

    private void btnIncreaseRangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIncreaseRangeActionPerformed
        for (int i = 0; i < amountButtons.size(); i++) {
            int buttonValue = Integer.valueOf(amountButtons.get(i).getText());
            buttonValue = buttonValue + amountButtons.size();
            amountButtons.get(i).setText(String.valueOf(buttonValue));
            
            if(buttonValue == product.getAmountSold()){
                amountButtons.get(i).setIcon(iconSelected);
            }else{
                amountButtons.get(i).setIcon(iconUnselected);
            }
        }
        if (!amountButtons.get(0).getText().equals("1")) {
            btnDecreseRange.setEnabled(true);
        }
    }//GEN-LAST:event_btnIncreaseRangeActionPerformed

    private void btnAmountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAmountActionPerformed
        JButton button = (JButton) evt.getSource();
        int buttonValue = Integer.valueOf(button.getText());
        if(buttonValue > 0){
            product.setAmountSold(buttonValue);
            parentFrame.editAmountOnBill(product);
        }
        this.dispose();
    }//GEN-LAST:event_btnAmountActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAmount1;
    private javax.swing.JButton btnAmount2;
    private javax.swing.JButton btnAmount3;
    private javax.swing.JButton btnAmount4;
    private javax.swing.JButton btnAmount5;
    private javax.swing.JButton btnDecreseRange;
    private javax.swing.JButton btnIncreaseRange;
    private javax.swing.JLabel lblProductImage;
    private javax.swing.JLabel lblProductName;
    private javax.swing.JLabel lblProductPrice;
    private javax.swing.JLabel lblSelectAmount;
    private javax.swing.JPanel pnlBottomPanel;
    private javax.swing.JPanel pnlSelectAmount;
    private javax.swing.JPanel pnlTopPanel;
    // End of variables declaration//GEN-END:variables
}
