/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package EposSimple.Widgets;

import EposSimple.EposSimpleApp;
import EposSimple.Models.SoldProduct;
import java.awt.Dimension;
import javax.swing.JPanel;

/**
 *
 * @author tg
 */
public class NotificationWidget extends javax.swing.JPanel {

    private EposSimpleApp parentFrame;

    /**
     * Creates new form BillPanel
     * @param parentFrame
     * @param total
     */
    public NotificationWidget(EposSimpleApp parentFrame, double total) {
        this.parentFrame = parentFrame;
        initComponents();
        
        lblMessage.setText("Purchase recorded (Total: £" + String.format("%.2f", total) + ")");
    }
    
    public void updateTotal(double total){
        lblMessage.setText("Purchase recorded (Total: £" + String.format("%.2f", total) + ")");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblMessage = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 255, 204));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 0)));
        setMaximumSize(new java.awt.Dimension(275, 53));
        setMinimumSize(new java.awt.Dimension(275, 0));
        setPreferredSize(new java.awt.Dimension(275, 0));
        setLayout(new java.awt.GridLayout(1, 0));

        lblMessage.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblMessage.setForeground(new java.awt.Color(0, 102, 0));
        lblMessage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMessage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-ok-20.png"))); // NOI18N
        lblMessage.setText("Purchased recorded (Total: £34.44)");
        lblMessage.setAlignmentX(0.5F);
        lblMessage.setMinimumSize(new java.awt.Dimension(0, 0));
        add(lblMessage);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblMessage;
    // End of variables declaration//GEN-END:variables
}
