/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package EposSimple.Widgets;

import EposSimple.Dialogs.AddEditUserDialog;
import EposSimple.EposSimpleApp;
import EposSimple.Models.Product;
import EposSimple.Models.Report;
import EposSimple.Models.User;
import EposSimple.Panels.ProductManagement;
import java.awt.Container;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.JDialog;
import javax.swing.SwingUtilities;

/**
 *
 * @author tg
 */
public class ProductListWidget extends javax.swing.JPanel {

    private EposSimpleApp parentFrame;
    private Product product;
    private ProductManagement parentPanel;

    /**
     * Creates new form BillPanel
     * @param parentFrame
     * @param parentPanel
     * @param product
     */
    public ProductListWidget(EposSimpleApp parentFrame, ProductManagement parentPanel, Product product) {
        this.parentFrame = parentFrame;
        this.parentPanel = parentPanel;
        this.product = product;
        
        initComponents();
        lblProductName.setText(this.product.getName());
        lblProductPrice.setText("£" + String.format("%.2f", this.product.getPrice()));
        lblProductImage.setIcon(this.product.getProductIcon(42, 42));
        if(this.product.getOrder() == 0){
            btnMoveUp.setEnabled(false);
        }
        if(this.product.isProductLastinOrder()){
            btnMoveDown.setEnabled(false);
        }
        
        MouseAdapter redispatcher = new MouseAdapterImpl();
        this.addMouseListener(redispatcher);
        this.addMouseMotionListener(redispatcher);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        pnlLeft = new javax.swing.JPanel();
        lblProductImage = new javax.swing.JLabel();
        lblProductName = new javax.swing.JLabel();
        lblSelected = new javax.swing.JLabel();
        pnlRight = new javax.swing.JPanel();
        lblProductPrice = new javax.swing.JLabel();
        pnlButtons = new javax.swing.JPanel();
        btnMoveDown = new javax.swing.JButton();
        btnMoveUp = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        setMaximumSize(new java.awt.Dimension(275, 68));
        setMinimumSize(new java.awt.Dimension(275, 68));
        setPreferredSize(new java.awt.Dimension(275, 68));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });
        java.awt.GridBagLayout layout1 = new java.awt.GridBagLayout();
        layout1.columnWeights = new double[] {1.0, 1.0};
        setLayout(layout1);

        pnlLeft.setBackground(new java.awt.Color(255, 255, 255));
        pnlLeft.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 15));
        pnlLeft.setLayout(new javax.swing.BoxLayout(pnlLeft, javax.swing.BoxLayout.LINE_AXIS));

        lblProductImage.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblProductImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/1608727_user_icon.png"))); // NOI18N
        lblProductImage.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 5));
        pnlLeft.add(lblProductImage);

        lblProductName.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblProductName.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblProductName.setText("Product Name");
        pnlLeft.add(lblProductName);

        lblSelected.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-ok-20.png"))); // NOI18N
        lblSelected.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 15, 1, 1));
        lblSelected.setVisible(false);
        pnlLeft.add(lblSelected);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        add(pnlLeft, gridBagConstraints);

        pnlRight.setBackground(new java.awt.Color(255, 255, 255));
        pnlRight.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 15, 1, 1));
        pnlRight.setLayout(new java.awt.GridLayout(2, 1));

        lblProductPrice.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblProductPrice.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblProductPrice.setText("£42.22");
        pnlRight.add(lblProductPrice);

        pnlButtons.setBackground(new java.awt.Color(255, 255, 255));
        pnlButtons.setLayout(new javax.swing.BoxLayout(pnlButtons, javax.swing.BoxLayout.LINE_AXIS));

        btnMoveDown.setBackground(new java.awt.Color(255, 255, 255));
        btnMoveDown.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-chevron-down-18.png"))); // NOI18N
        btnMoveDown.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 10, 5, 10));
        btnMoveDown.setBorderPainted(false);
        btnMoveDown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMoveDownActionPerformed(evt);
            }
        });
        pnlButtons.add(btnMoveDown);

        btnMoveUp.setBackground(new java.awt.Color(255, 255, 255));
        btnMoveUp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-chevron-up-18.png"))); // NOI18N
        btnMoveUp.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 10, 5, 10));
        btnMoveUp.setBorderPainted(false);
        btnMoveUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMoveUpActionPerformed(evt);
            }
        });
        pnlButtons.add(btnMoveUp);

        pnlRight.add(pnlButtons);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        add(pnlRight, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void btnMoveDownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMoveDownActionPerformed
        parentFrame.moveProductOrder("down", this.product.getId());
    }//GEN-LAST:event_btnMoveDownActionPerformed

    private void btnMoveUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMoveUpActionPerformed
        parentFrame.moveProductOrder("up", this.product.getId());
    }//GEN-LAST:event_btnMoveUpActionPerformed

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        parentPanel.selectProduct(this, product);
    }//GEN-LAST:event_formMouseClicked

    public void deselect(){
        lblSelected.setVisible(false);
    }
    public void select(){
        lblSelected.setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMoveDown;
    private javax.swing.JButton btnMoveUp;
    private javax.swing.JLabel lblProductImage;
    private javax.swing.JLabel lblProductName;
    private javax.swing.JLabel lblProductPrice;
    private javax.swing.JLabel lblSelected;
    private javax.swing.JPanel pnlButtons;
    private javax.swing.JPanel pnlLeft;
    private javax.swing.JPanel pnlRight;
    // End of variables declaration//GEN-END:variables

    private class MouseAdapterImpl extends MouseAdapter {

        public MouseAdapterImpl() {
        }

        @Override
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            formMouseClicked(evt);
        }

        @Override
        public void mouseEntered(MouseEvent evt) {
            dispatchMouseEvent(evt);
        }

        @Override
        public void mouseExited(MouseEvent evt) {
            dispatchMouseEvent(evt);
        }

        @Override
        public void mouseMoved(MouseEvent evt) {
            dispatchMouseEvent(evt);
        }

        @Override
        public void mousePressed(MouseEvent evt) {
            dispatchMouseEvent(evt);
        }

        @Override
        public void mouseReleased(MouseEvent evt) {
            dispatchMouseEvent(evt);
        }

        @Override
        public void mouseDragged(MouseEvent evt) {
            dispatchMouseEvent(evt);
        }

        private void dispatchMouseEvent(MouseEvent evt) {
            Container parent = evt.getComponent().getParent();
            parent.dispatchEvent(SwingUtilities.convertMouseEvent(evt.getComponent(), evt, parent));
        }
    }
}
