/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package EposSimple.Widgets;

import EposSimple.EposSimpleApp;
import EposSimple.Models.Sale;
import EposSimple.Models.SoldProduct;
import java.text.SimpleDateFormat;

/**
 *
 * @author tg
 */
public class SaleListWidget extends javax.swing.JPanel {

    private EposSimpleApp parentFrame;
    private SoldProduct product;

    /**
     * Creates new form BillPanel
     */
    public SaleListWidget(EposSimpleApp parentFrame, Sale sale) {
        this.parentFrame = parentFrame;
        this.product = product;
        initComponents();
        lblSaleDateTime.setText(new SimpleDateFormat("yyyy-MM-dd HH:mm:ss").format(sale.getDate()));
        lblSaleUser.setText("(" + sale.getSoldBy().getLogin() + ")");
        lblSaleTotal.setText("£ " + String.format("%.2f", sale.getTotalValue()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        pnlLeft = new javax.swing.JPanel();
        lblSaleDateTime = new javax.swing.JLabel();
        lblSaleUser = new javax.swing.JLabel();
        pnlRight = new javax.swing.JPanel();
        lblTotal = new javax.swing.JLabel();
        lblSaleTotal = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        setMaximumSize(new java.awt.Dimension(275, 53));
        setMinimumSize(new java.awt.Dimension(275, 53));
        setPreferredSize(new java.awt.Dimension(275, 53));
        java.awt.GridBagLayout layout1 = new java.awt.GridBagLayout();
        layout1.columnWeights = new double[] {1.0, 1.0};
        setLayout(layout1);

        pnlLeft.setBackground(new java.awt.Color(255, 255, 255));
        pnlLeft.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 15));
        pnlLeft.setLayout(new java.awt.GridLayout(0, 1));

        lblSaleDateTime.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblSaleDateTime.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblSaleDateTime.setText("24/03/2022");
        pnlLeft.add(lblSaleDateTime);

        lblSaleUser.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblSaleUser.setText("15:44");
        lblSaleUser.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 5));
        pnlLeft.add(lblSaleUser);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        add(pnlLeft, gridBagConstraints);

        pnlRight.setBackground(new java.awt.Color(255, 255, 255));
        pnlRight.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 15, 1, 1));
        pnlRight.setLayout(new java.awt.GridLayout(2, 1));

        lblTotal.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblTotal.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTotal.setText("Total:");
        pnlRight.add(lblTotal);

        lblSaleTotal.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblSaleTotal.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblSaleTotal.setText("£34.22");
        lblSaleTotal.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 5));
        pnlRight.add(lblSaleTotal);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        add(pnlRight, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblSaleDateTime;
    private javax.swing.JLabel lblSaleTotal;
    private javax.swing.JLabel lblSaleUser;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JPanel pnlLeft;
    private javax.swing.JPanel pnlRight;
    // End of variables declaration//GEN-END:variables
}
