/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package EposSimple.Widgets;

import EposSimple.Dialogs.AddEditUserDialog;
import EposSimple.Dialogs.ProductAmountDialog;
import EposSimple.EposSimpleApp;
import EposSimple.Models.Report;
import EposSimple.Models.SoldProduct;
import EposSimple.Models.User;
import EposSimple.Panels.UserManagement;
import java.awt.Container;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.text.SimpleDateFormat;
import javax.swing.JDialog;
import javax.swing.SwingUtilities;

/**
 *
 * @author tg
 */
public class UserListWidget extends javax.swing.JPanel {

    private EposSimpleApp parentFrame;
    private Report report;
    private User user;
    private UserManagement parentPanel;

    /**
     * Creates new form BillPanel
     * @param parentFrame
     * @param user
     */
    public UserListWidget(EposSimpleApp parentFrame, UserManagement parentPanel, Report report) {
        this.parentFrame = parentFrame;
        this.parentPanel = parentPanel;
        this.report = report;
        this.user = report.getUser();
        initComponents();
        lblUserName.setText(this.user.getLogin());
        if(this.user.getRole() == 0){
            lblUserRole.setText("Manager");
        }else{
            lblUserRole.setText("Sales Agent");
        }
        MouseAdapter redispatcher = new MouseAdapterImpl();
        this.addMouseListener(redispatcher);
        this.addMouseMotionListener(redispatcher);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        pnlLeft = new javax.swing.JPanel();
        lblUserIcon = new javax.swing.JLabel();
        lblUserName = new javax.swing.JLabel();
        lblSelected = new javax.swing.JLabel();
        pnlRight = new javax.swing.JPanel();
        lblUserRole = new javax.swing.JLabel();
        pnlButtons = new javax.swing.JPanel();
        btnEdit = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        setMaximumSize(new java.awt.Dimension(275, 68));
        setMinimumSize(new java.awt.Dimension(275, 68));
        setPreferredSize(new java.awt.Dimension(275, 68));
        java.awt.GridBagLayout layout1 = new java.awt.GridBagLayout();
        layout1.columnWeights = new double[] {1.0, 1.0};
        setLayout(layout1);

        pnlLeft.setBackground(new java.awt.Color(255, 255, 255));
        pnlLeft.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 15));
        pnlLeft.setLayout(new javax.swing.BoxLayout(pnlLeft, javax.swing.BoxLayout.LINE_AXIS));

        lblUserIcon.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblUserIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/1608727_user_icon.png"))); // NOI18N
        lblUserIcon.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 5));
        pnlLeft.add(lblUserIcon);

        lblUserName.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblUserName.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblUserName.setText("User Name");
        pnlLeft.add(lblUserName);

        lblSelected.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-ok-20.png"))); // NOI18N
        lblSelected.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 15, 1, 1));
        lblSelected.setVisible(false);
        pnlLeft.add(lblSelected);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        add(pnlLeft, gridBagConstraints);

        pnlRight.setBackground(new java.awt.Color(255, 255, 255));
        pnlRight.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 15, 1, 1));
        pnlRight.setLayout(new java.awt.GridLayout(2, 1));

        lblUserRole.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblUserRole.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUserRole.setText("Manager");
        pnlRight.add(lblUserRole);

        pnlButtons.setBackground(new java.awt.Color(255, 255, 255));
        pnlButtons.setLayout(new javax.swing.BoxLayout(pnlButtons, javax.swing.BoxLayout.LINE_AXIS));

        btnEdit.setBackground(new java.awt.Color(255, 255, 255));
        btnEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-settings-24.png"))); // NOI18N
        btnEdit.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 10, 0, 10));
        btnEdit.setBorderPainted(false);
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });
        pnlButtons.add(btnEdit);

        btnDelete.setBackground(new java.awt.Color(255, 255, 255));
        btnDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-remove-24.png"))); // NOI18N
        btnDelete.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 10, 0, 10));
        btnDelete.setBorderPainted(false);
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        pnlButtons.add(btnDelete);

        pnlRight.add(pnlButtons);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        add(pnlRight, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        java.awt.EventQueue.invokeLater(() -> {
            JDialog d = new AddEditUserDialog(parentFrame, user);
            d.setVisible(true);
        });
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        parentFrame.deleteUser(user);
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void formMouseClicked(java.awt.event.MouseEvent evt){
        parentPanel.selectUser(this, report);
    }
    
    public void deselect(){
        lblSelected.setVisible(false);
    }
    public void select(){
        lblSelected.setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEdit;
    private javax.swing.JLabel lblSelected;
    private javax.swing.JLabel lblUserIcon;
    private javax.swing.JLabel lblUserName;
    private javax.swing.JLabel lblUserRole;
    private javax.swing.JPanel pnlButtons;
    private javax.swing.JPanel pnlLeft;
    private javax.swing.JPanel pnlRight;
    // End of variables declaration//GEN-END:variables

    private class MouseAdapterImpl extends MouseAdapter {

        public MouseAdapterImpl() {
        }

        @Override
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            formMouseClicked(evt);
        }

        @Override
        public void mouseEntered(MouseEvent evt) {
            dispatchMouseEvent(evt);
        }

        @Override
        public void mouseExited(MouseEvent evt) {
            dispatchMouseEvent(evt);
        }

        @Override
        public void mouseMoved(MouseEvent evt) {
            dispatchMouseEvent(evt);
        }

        @Override
        public void mousePressed(MouseEvent evt) {
            dispatchMouseEvent(evt);
        }

        @Override
        public void mouseReleased(MouseEvent evt) {
            dispatchMouseEvent(evt);
        }

        @Override
        public void mouseDragged(MouseEvent evt) {
            dispatchMouseEvent(evt);
        }

        private void dispatchMouseEvent(MouseEvent evt) {
            Container parent = evt.getComponent().getParent();
            parent.dispatchEvent(SwingUtilities.convertMouseEvent(evt.getComponent(), evt, parent));
        }
    }
}
