package EposSimple.Panels;

import EposSimple.EposSimpleApp;
import EposSimple.Models.User;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

/**
 *
 * @author tg
 */
public class Login extends javax.swing.JPanel {

    private final ArrayList<User> users;

    /**
     * Creates new form LoginPanel
     *
     */
    public Login() {
        initComponents();
        users = new ArrayList<>();
        cboPinpadUser.setModel(new DefaultComboBoxModel(this.users.toArray()));
    }

    public Login(ArrayList<User> users) {
        initComponents();
        this.users = users;
        cboPinpadUser.setModel(new DefaultComboBoxModel(this.users.toArray()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblPinpadUser = new javax.swing.JLabel();
        cboPinpadUser = new javax.swing.JComboBox<>();
        lblPinpadPin = new javax.swing.JLabel();
        txtPinpadPin = new javax.swing.JPasswordField();
        pnlKeypad = new javax.swing.JPanel();
        btnPinpad7 = new javax.swing.JButton();
        btnPinpad8 = new javax.swing.JButton();
        btnPinpad9 = new javax.swing.JButton();
        btnPinpad4 = new javax.swing.JButton();
        btnPinpad5 = new javax.swing.JButton();
        btnPinpad6 = new javax.swing.JButton();
        btnPinpad1 = new javax.swing.JButton();
        btnPinpad2 = new javax.swing.JButton();
        btnPinpad3 = new javax.swing.JButton();
        btnPinpadBackspace = new javax.swing.JButton();
        btnPinpad0 = new javax.swing.JButton();
        btnPinpadOk = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(309, 500));
        setMinimumSize(new java.awt.Dimension(309, 500));
        setName("Login Panel"); // NOI18N
        setPreferredSize(new java.awt.Dimension(309, 500));

        lblPinpadUser.setText("USER:");

        cboPinpadUser.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cboPinpadUser.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblPinpadPin.setText("PIN:");

        txtPinpadPin.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtPinpadPin.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtPinpadPin.setToolTipText("");
        txtPinpadPin.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtPinpadPin.setMargin(new java.awt.Insets(8, 10, 8, 10));

        pnlKeypad.setBackground(new java.awt.Color(255, 255, 255));
        pnlKeypad.setLayout(new java.awt.GridLayout(0, 3));

        btnPinpad7.setBackground(new java.awt.Color(255, 255, 255));
        btnPinpad7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnPinpad7.setText("7");
        btnPinpad7.setBorderPainted(false);
        btnPinpad7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPinpadButtonPushed(evt);
            }
        });
        pnlKeypad.add(btnPinpad7);

        btnPinpad8.setBackground(new java.awt.Color(255, 255, 255));
        btnPinpad8.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnPinpad8.setText("8");
        btnPinpad8.setBorderPainted(false);
        btnPinpad8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPinpadButtonPushed(evt);
            }
        });
        pnlKeypad.add(btnPinpad8);

        btnPinpad9.setBackground(new java.awt.Color(255, 255, 255));
        btnPinpad9.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnPinpad9.setText("9");
        btnPinpad9.setBorderPainted(false);
        btnPinpad9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPinpadButtonPushed(evt);
            }
        });
        pnlKeypad.add(btnPinpad9);

        btnPinpad4.setBackground(new java.awt.Color(255, 255, 255));
        btnPinpad4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnPinpad4.setText("4");
        btnPinpad4.setBorderPainted(false);
        btnPinpad4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPinpadButtonPushed(evt);
            }
        });
        pnlKeypad.add(btnPinpad4);

        btnPinpad5.setBackground(new java.awt.Color(255, 255, 255));
        btnPinpad5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnPinpad5.setText("5");
        btnPinpad5.setBorderPainted(false);
        btnPinpad5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPinpadButtonPushed(evt);
            }
        });
        pnlKeypad.add(btnPinpad5);

        btnPinpad6.setBackground(new java.awt.Color(255, 255, 255));
        btnPinpad6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnPinpad6.setText("6");
        btnPinpad6.setBorderPainted(false);
        btnPinpad6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPinpadButtonPushed(evt);
            }
        });
        pnlKeypad.add(btnPinpad6);

        btnPinpad1.setBackground(new java.awt.Color(255, 255, 255));
        btnPinpad1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnPinpad1.setText("1");
        btnPinpad1.setBorderPainted(false);
        btnPinpad1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPinpadButtonPushed(evt);
            }
        });
        pnlKeypad.add(btnPinpad1);

        btnPinpad2.setBackground(new java.awt.Color(255, 255, 255));
        btnPinpad2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnPinpad2.setText("2");
        btnPinpad2.setBorderPainted(false);
        btnPinpad2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPinpadButtonPushed(evt);
            }
        });
        pnlKeypad.add(btnPinpad2);

        btnPinpad3.setBackground(new java.awt.Color(255, 255, 255));
        btnPinpad3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnPinpad3.setText("3");
        btnPinpad3.setBorderPainted(false);
        btnPinpad3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPinpadButtonPushed(evt);
            }
        });
        pnlKeypad.add(btnPinpad3);

        btnPinpadBackspace.setBackground(new java.awt.Color(255, 255, 255));
        btnPinpadBackspace.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnPinpadBackspace.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-clear-symbol-50.png"))); // NOI18N
        btnPinpadBackspace.setBorderPainted(false);
        btnPinpadBackspace.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPinpadBackspaceActionPerformed(evt);
            }
        });
        pnlKeypad.add(btnPinpadBackspace);

        btnPinpad0.setBackground(new java.awt.Color(255, 255, 255));
        btnPinpad0.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnPinpad0.setText("0");
        btnPinpad0.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnPinpad0.setBorderPainted(false);
        btnPinpad0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPinpadButtonPushed(evt);
            }
        });
        pnlKeypad.add(btnPinpad0);

        btnPinpadOk.setBackground(new java.awt.Color(255, 255, 255));
        btnPinpadOk.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnPinpadOk.setText("OK");
        btnPinpadOk.setBorder(null);
        btnPinpadOk.setBorderPainted(false);
        btnPinpadOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPinpadOkActionPerformed(evt);
            }
        });
        pnlKeypad.add(btnPinpadOk);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblPinpadPin)
                    .addComponent(lblPinpadUser)
                    .addComponent(cboPinpadUser, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtPinpadPin)
                    .addComponent(pnlKeypad, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(106, Short.MAX_VALUE)
                .addComponent(lblPinpadUser)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cboPinpadUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblPinpadPin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPinpadPin, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlKeypad, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnPinpadOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPinpadOkActionPerformed
        User selectedUser = (User) cboPinpadUser.getSelectedItem();
        if (String.valueOf(selectedUser.getPin()).equals(new String(txtPinpadPin.getPassword()))) {
            ((EposSimpleApp) SwingUtilities.getWindowAncestor(this)).loginUser(selectedUser);
            txtPinpadPin.setText("");
        } else {
            txtPinpadPin.setText("");
            JOptionPane.showMessageDialog(null, "Wrong PIN for selected User.",
                    "Inane error",
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnPinpadOkActionPerformed

    private void btnPinpadBackspaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPinpadBackspaceActionPerformed
        if (txtPinpadPin.getPassword().length != 0) {
            txtPinpadPin.setText(new String(txtPinpadPin.getPassword()).substring(0, txtPinpadPin.getPassword().length - 1));
        }
    }//GEN-LAST:event_btnPinpadBackspaceActionPerformed

    private void btnPinpadButtonPushed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPinpadButtonPushed
        concateToPin(((JButton) evt.getSource()).getText());
    }//GEN-LAST:event_btnPinpadButtonPushed

    private void concateToPin(String buttonString) {
        if (txtPinpadPin.getPassword().length == 0) {
            txtPinpadPin.setText(buttonString);
        } else {
            txtPinpadPin.setText(new String(txtPinpadPin.getPassword()) + buttonString);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPinpad0;
    private javax.swing.JButton btnPinpad1;
    private javax.swing.JButton btnPinpad2;
    private javax.swing.JButton btnPinpad3;
    private javax.swing.JButton btnPinpad4;
    private javax.swing.JButton btnPinpad5;
    private javax.swing.JButton btnPinpad6;
    private javax.swing.JButton btnPinpad7;
    private javax.swing.JButton btnPinpad8;
    private javax.swing.JButton btnPinpad9;
    private javax.swing.JButton btnPinpadBackspace;
    private javax.swing.JButton btnPinpadOk;
    private javax.swing.JComboBox<String> cboPinpadUser;
    private javax.swing.JLabel lblPinpadPin;
    private javax.swing.JLabel lblPinpadUser;
    private javax.swing.JPanel pnlKeypad;
    private javax.swing.JPasswordField txtPinpadPin;
    // End of variables declaration//GEN-END:variables
}
