/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package EposSimple.Panels;

import EposSimple.EposSimpleApp;
import EposSimple.Helpers.*;
import EposSimple.Models.*;
import EposSimple.Widgets.SaleListWidget;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.BorderFactory;
import javax.swing.JComboBox;

/**
 *
 * @author tg
 */
public class Reports extends javax.swing.JPanel {

    User loggedUser;
    EposSimpleApp parentFrame;
    ArrayList<Sale> sales;
    ArrayList<Report> reports;
    ArrayList<User> users;

    /**
     * Creates new form SalesDashboard
     *
     * @param parentFrame
     * @param loggedUser
     * @param sales
     * @param users
     */
    public Reports(EposSimpleApp parentFrame, User loggedUser, ArrayList<Sale> sales, ArrayList<User> users) {
        this.loggedUser = loggedUser;
        this.parentFrame = parentFrame;
        this.sales = sales;
        this.users = users;
        initComponents();
        Sale sale;
        for (int i = sales.size() - 1; i >= 0; i--) {
            if(sales.get(i).getSoldBy().getId() == loggedUser.getId() || loggedUser.getRole() == 0){
                sale = sales.get(i);
                pnlSalesList.add(new SaleListWidget(parentFrame, sale));
            }
        }
        pnlSalesList.validate();
        pnlSalesList.repaint();

        DragScrollListener listener = new DragScrollListener(pnlSalesList);
        pnlSalesList.addMouseListener(listener);
        pnlSalesList.addMouseMotionListener(listener);

        reports = new ArrayList<>();
        if (loggedUser.getRole() == 0){
            reports.add(new Report(sales));
            for (User user : this.users) {
                reports.add(new Report(sales, user));
            }
        }else{
            reports.add(new Report(sales, loggedUser));
            cboSelectReport.setEnabled(false);
        }
        ArrayListComboBoxModel model = new ArrayListComboBoxModel(reports);
        cboSelectReport.setModel(model);
        cboSelectReport.setSelectedIndex(0);
        
        if(loggedUser.getRole() == 1){
            btnResetAllSales.setVisible(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        srllPanel = new CustomScrollPane();
        pnlSalesList = new javax.swing.JPanel();
        lblSalesHistory = new javax.swing.JLabel();
        pnlRightPanel = new javax.swing.JPanel();
        pnlAligningPane = new javax.swing.JPanel();
        pnlReport = new javax.swing.JPanel();
        lblSelectReport = new javax.swing.JLabel();
        cboSelectReport = new javax.swing.JComboBox<>();
        lblSelected = new javax.swing.JLabel();
        lblSelectedValue = new javax.swing.JLabel();
        lblTotalCustomers = new javax.swing.JLabel();
        lblTotalCustomersValue = new javax.swing.JLabel();
        lblAverageSale = new javax.swing.JLabel();
        lblAverageSaleValue = new javax.swing.JLabel();
        lblMinimalSale = new javax.swing.JLabel();
        lblMinimalSaleValue = new javax.swing.JLabel();
        lblMaximumSale = new javax.swing.JLabel();
        lblMaximumSaleValue = new javax.swing.JLabel();
        lblTotalSales = new javax.swing.JLabel();
        lblTotalSalesValue = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnResetAllSales = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(BorderFactory.createMatteBorder(1, 0, 0, 0, Color.BLACK));
        setMaximumSize(new java.awt.Dimension(1260, 626));
        setMinimumSize(new java.awt.Dimension(1260, 626));
        setPreferredSize(new java.awt.Dimension(1260, 626));
        setLayout(new java.awt.GridBagLayout());

        srllPanel.setBackground(new java.awt.Color(255, 255, 255));
        srllPanel.setBorder(null);
        srllPanel.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        srllPanel.setPreferredSize(new java.awt.Dimension(314, 604));

        pnlSalesList.setBackground(new java.awt.Color(255, 255, 255));
        pnlSalesList.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        pnlSalesList.setLayout(new javax.swing.BoxLayout(pnlSalesList, javax.swing.BoxLayout.PAGE_AXIS));

        lblSalesHistory.setBackground(new java.awt.Color(255, 255, 255));
        lblSalesHistory.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblSalesHistory.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblSalesHistory.setText("Sales history:");
        lblSalesHistory.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        pnlSalesList.add(lblSalesHistory);

        srllPanel.setViewportView(pnlSalesList);

        add(srllPanel, new java.awt.GridBagConstraints());

        pnlRightPanel.setBackground(new java.awt.Color(255, 255, 255));
        pnlRightPanel.setPreferredSize(new java.awt.Dimension(930, 604));
        pnlRightPanel.setLayout(new javax.swing.BoxLayout(pnlRightPanel, javax.swing.BoxLayout.PAGE_AXIS));

        pnlAligningPane.setLayout(new javax.swing.BoxLayout(pnlAligningPane, javax.swing.BoxLayout.LINE_AXIS));

        pnlReport.setBackground(new java.awt.Color(255, 255, 255));
        pnlReport.setLayout(new java.awt.GridBagLayout());

        lblSelectReport.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblSelectReport.setText("Select report to view:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.ipadx = 10;
        gridBagConstraints.ipady = 50;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        pnlReport.add(lblSelectReport, gridBagConstraints);

        cboSelectReport.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cboSelectReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboSelectReportActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        pnlReport.add(cboSelectReport, gridBagConstraints);

        lblSelected.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblSelected.setText("Selected:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 10;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        pnlReport.add(lblSelected, gridBagConstraints);

        lblSelectedValue.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblSelectedValue.setText("Report for User 1");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        pnlReport.add(lblSelectedValue, gridBagConstraints);

        lblTotalCustomers.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblTotalCustomers.setText("Total customers served:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 10;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        pnlReport.add(lblTotalCustomers, gridBagConstraints);

        lblTotalCustomersValue.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblTotalCustomersValue.setText("153");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        pnlReport.add(lblTotalCustomersValue, gridBagConstraints);

        lblAverageSale.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblAverageSale.setText("Average sale value:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 4;
        gridBagConstraints.ipadx = 10;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        pnlReport.add(lblAverageSale, gridBagConstraints);

        lblAverageSaleValue.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblAverageSaleValue.setText("£45.22");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        pnlReport.add(lblAverageSaleValue, gridBagConstraints);

        lblMinimalSale.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblMinimalSale.setText("Minimal sale value:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 5;
        gridBagConstraints.ipadx = 10;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        pnlReport.add(lblMinimalSale, gridBagConstraints);

        lblMinimalSaleValue.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblMinimalSaleValue.setText("£3.45");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        pnlReport.add(lblMinimalSaleValue, gridBagConstraints);

        lblMaximumSale.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblMaximumSale.setText("Maximum sale value:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 6;
        gridBagConstraints.ipadx = 10;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        pnlReport.add(lblMaximumSale, gridBagConstraints);

        lblMaximumSaleValue.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblMaximumSaleValue.setText("£548.00");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        pnlReport.add(lblMaximumSaleValue, gridBagConstraints);

        lblTotalSales.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblTotalSales.setText("Total sales value:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 3;
        gridBagConstraints.ipadx = 10;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        pnlReport.add(lblTotalSales, gridBagConstraints);

        lblTotalSalesValue.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblTotalSalesValue.setText("£3500.42");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        pnlReport.add(lblTotalSalesValue, gridBagConstraints);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("aaaa");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 9;
        pnlReport.add(jLabel1, gridBagConstraints);

        btnResetAllSales.setBackground(new java.awt.Color(255, 255, 255));
        btnResetAllSales.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnResetAllSales.setText("Reset All Sales");
        btnResetAllSales.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnResetAllSales.setBorderPainted(false);
        btnResetAllSales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetAllSalesActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipady = 25;
        pnlReport.add(btnResetAllSales, gridBagConstraints);

        pnlAligningPane.add(pnlReport);

        pnlRightPanel.add(pnlAligningPane);

        add(pnlRightPanel, new java.awt.GridBagConstraints());
    }// </editor-fold>//GEN-END:initComponents

    private void cboSelectReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboSelectReportActionPerformed
        updateShownReport((Report) cboSelectReport.getSelectedItem());
    }//GEN-LAST:event_cboSelectReportActionPerformed

    private void btnResetAllSalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetAllSalesActionPerformed
        parentFrame.resetAllSales();
    }//GEN-LAST:event_btnResetAllSalesActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnResetAllSales;
    private javax.swing.JComboBox<String> cboSelectReport;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblAverageSale;
    private javax.swing.JLabel lblAverageSaleValue;
    private javax.swing.JLabel lblMaximumSale;
    private javax.swing.JLabel lblMaximumSaleValue;
    private javax.swing.JLabel lblMinimalSale;
    private javax.swing.JLabel lblMinimalSaleValue;
    private javax.swing.JLabel lblSalesHistory;
    private javax.swing.JLabel lblSelectReport;
    private javax.swing.JLabel lblSelected;
    private javax.swing.JLabel lblSelectedValue;
    private javax.swing.JLabel lblTotalCustomers;
    private javax.swing.JLabel lblTotalCustomersValue;
    private javax.swing.JLabel lblTotalSales;
    private javax.swing.JLabel lblTotalSalesValue;
    private javax.swing.JPanel pnlAligningPane;
    private javax.swing.JPanel pnlReport;
    private javax.swing.JPanel pnlRightPanel;
    private javax.swing.JPanel pnlSalesList;
    private javax.swing.JScrollPane srllPanel;
    // End of variables declaration//GEN-END:variables

    private void updateShownReport(Report selectedReport) {
        String reportName = selectedReport.getReportName();
        lblSelectedValue.setText(reportName);
        
        double totalSalesValue = selectedReport.getTotalSalesValue();
        lblTotalSalesValue.setText("£" + String.format("%.2f", totalSalesValue));
        
        double totalCusotmersValue = selectedReport.getTotalCustomerServed();
        lblTotalCustomersValue.setText(String.format("%.0f", totalCusotmersValue));
        
        double averageSaleValue = selectedReport.getAvgSaleValue();
        lblAverageSaleValue.setText("£" + String.format("%.2f", averageSaleValue));
        
        double minimalSaleValue = selectedReport.getMinSaleValue();
        lblMinimalSaleValue.setText("£" + String.format("%.2f", minimalSaleValue));
        
        double maximumSaleValue = selectedReport.getMaxSaleValue();
        lblMaximumSaleValue.setText("£" + String.format("%.2f", maximumSaleValue));

    }

}
