package EposSimple.Panels;

import EposSimple.EposSimpleApp;
import EposSimple.Models.User;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.SwingUtilities;
import javax.swing.Timer;

/**
 *
 * @author tg
 */
public class TopMenu extends javax.swing.JPanel {

    private final User loggedUser;
    private Timer timer;

    /**
     * Creates new form TopMenu
     */
    public TopMenu() {
        this.loggedUser = new User("", 0, 1);
        initComponents();
    }

    /**
     *
     * @param parentFrame
     * @param loggedUser
     */
    public TopMenu(EposSimpleApp parentFrame, User loggedUser) {
        this.loggedUser = loggedUser;
        initComponents();

        btnUserMenu.setText(loggedUser.getLogin());
        ActionListener updateClock = new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                Date date = new Date();
                DateFormat timeFormat = new SimpleDateFormat("HH:mm:ss");
                String time = timeFormat.format(date);
                lblClock.setText(time);
            }
        };
        timer = new Timer(1000, updateClock);
        timer.setInitialDelay(0);
        timer.start();

        if (this.loggedUser.getRole() == 1) {
            btnUsersManagement.setVisible(false);
            btnProductManagement.setVisible(false);
            sep2.setVisible(false);
            sep3.setVisible(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        popupUserMenu = new javax.swing.JPopupMenu();
        mnuAccountDetails = new javax.swing.JMenuItem();
        mnuLogout = new javax.swing.JMenuItem();
        mnuExit = new javax.swing.JMenuItem();
        pnlLeftSide = new javax.swing.JPanel();
        btnDashboard = new javax.swing.JButton();
        sep1 = new javax.swing.JSeparator();
        btnReports = new javax.swing.JButton();
        sep2 = new javax.swing.JSeparator();
        btnUsersManagement = new javax.swing.JButton();
        sep3 = new javax.swing.JSeparator();
        btnProductManagement = new javax.swing.JButton();
        pnlRightSide = new javax.swing.JPanel();
        lblClock = new javax.swing.JLabel();
        btnUserMenu = new javax.swing.JButton();

        popupUserMenu.setBackground(new java.awt.Color(255, 255, 255));
        popupUserMenu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        mnuAccountDetails.setBackground(new java.awt.Color(255, 255, 255));
        mnuAccountDetails.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-user-24.png"))); // NOI18N
        mnuAccountDetails.setText("Account Details");
        mnuAccountDetails.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mnuAccountDetails.setMargin(new java.awt.Insets(8, 8, 8, 8));
        mnuAccountDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuAccountDetailsActionPerformed(evt);
            }
        });
        popupUserMenu.add(mnuAccountDetails);

        mnuLogout.setBackground(new java.awt.Color(255, 255, 255));
        mnuLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-settings-24.png"))); // NOI18N
        mnuLogout.setText("Logout");
        mnuLogout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mnuLogout.setMargin(new java.awt.Insets(8, 8, 8, 8));
        mnuLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuLogoutActionPerformed(evt);
            }
        });
        popupUserMenu.add(mnuLogout);

        mnuExit.setBackground(new java.awt.Color(255, 255, 255));
        mnuExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-fire-exit-24.png"))); // NOI18N
        mnuExit.setText("Exit");
        mnuExit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mnuExit.setMargin(new java.awt.Insets(8, 8, 8, 8));
        mnuExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuExitActionPerformed(evt);
            }
        });
        popupUserMenu.add(mnuExit);

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(1260, 55));
        setMinimumSize(new java.awt.Dimension(1260, 55));
        setName("Top Menu"); // NOI18N
        setPreferredSize(new java.awt.Dimension(1260, 55));
        setLayout(new java.awt.GridBagLayout());

        pnlLeftSide.setBackground(new java.awt.Color(255, 255, 255));
        pnlLeftSide.setMaximumSize(new java.awt.Dimension(980, 55));
        pnlLeftSide.setMinimumSize(new java.awt.Dimension(980, 55));
        pnlLeftSide.setPreferredSize(new java.awt.Dimension(980, 55));
        pnlLeftSide.setLayout(new javax.swing.BoxLayout(pnlLeftSide, javax.swing.BoxLayout.LINE_AXIS));

        btnDashboard.setBackground(new java.awt.Color(255, 255, 255));
        btnDashboard.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnDashboard.setForeground(java.awt.SystemColor.textHighlight);
        btnDashboard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-cash-counter-28.png"))); // NOI18N
        btnDashboard.setText("Sales Dashboard");
        btnDashboard.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnDashboard.setBorderPainted(false);
        btnDashboard.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDashboard.setMaximumSize(new java.awt.Dimension(180, 55));
        btnDashboard.setMinimumSize(new java.awt.Dimension(180, 55));
        btnDashboard.setPreferredSize(new java.awt.Dimension(180, 55));
        btnDashboard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDashboardActionPerformed(evt);
            }
        });
        pnlLeftSide.add(btnDashboard);

        sep1.setForeground(new java.awt.Color(0, 0, 0));
        sep1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        sep1.setMaximumSize(new java.awt.Dimension(1, 35));
        sep1.setMinimumSize(new java.awt.Dimension(1, 35));
        sep1.setPreferredSize(new java.awt.Dimension(1, 35));
        pnlLeftSide.add(sep1);

        btnReports.setBackground(new java.awt.Color(255, 255, 255));
        btnReports.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnReports.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-total-sales-28.png"))); // NOI18N
        btnReports.setText("Reports");
        btnReports.setBorderPainted(false);
        btnReports.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnReports.setMaximumSize(new java.awt.Dimension(120, 55));
        btnReports.setMinimumSize(new java.awt.Dimension(120, 55));
        btnReports.setPreferredSize(new java.awt.Dimension(120, 55));
        btnReports.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportsActionPerformed(evt);
            }
        });
        pnlLeftSide.add(btnReports);

        sep2.setForeground(new java.awt.Color(0, 0, 0));
        sep2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        sep2.setMaximumSize(new java.awt.Dimension(1, 35));
        sep2.setMinimumSize(new java.awt.Dimension(1, 35));
        sep2.setPreferredSize(new java.awt.Dimension(1, 35));
        pnlLeftSide.add(sep2);

        btnUsersManagement.setBackground(new java.awt.Color(255, 255, 255));
        btnUsersManagement.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnUsersManagement.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-user-28.png"))); // NOI18N
        btnUsersManagement.setText("User Management");
        btnUsersManagement.setBorderPainted(false);
        btnUsersManagement.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnUsersManagement.setMaximumSize(new java.awt.Dimension(180, 55));
        btnUsersManagement.setMinimumSize(new java.awt.Dimension(180, 55));
        btnUsersManagement.setPreferredSize(new java.awt.Dimension(180, 55));
        btnUsersManagement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUsersManagementActionPerformed(evt);
            }
        });
        pnlLeftSide.add(btnUsersManagement);

        sep3.setForeground(new java.awt.Color(0, 0, 0));
        sep3.setOrientation(javax.swing.SwingConstants.VERTICAL);
        sep3.setMaximumSize(new java.awt.Dimension(1, 35));
        sep3.setMinimumSize(new java.awt.Dimension(1, 35));
        sep3.setPreferredSize(new java.awt.Dimension(1, 35));
        pnlLeftSide.add(sep3);

        btnProductManagement.setBackground(new java.awt.Color(255, 255, 255));
        btnProductManagement.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnProductManagement.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-product-28.png"))); // NOI18N
        btnProductManagement.setText("Product Management");
        btnProductManagement.setBorderPainted(false);
        btnProductManagement.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnProductManagement.setMaximumSize(new java.awt.Dimension(200, 55));
        btnProductManagement.setMinimumSize(new java.awt.Dimension(0, 55));
        btnProductManagement.setPreferredSize(new java.awt.Dimension(180, 55));
        btnProductManagement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProductManagementActionPerformed(evt);
            }
        });
        pnlLeftSide.add(btnProductManagement);

        add(pnlLeftSide, new java.awt.GridBagConstraints());

        pnlRightSide.setBackground(new java.awt.Color(255, 255, 255));
        pnlRightSide.setMaximumSize(new java.awt.Dimension(300, 55));
        pnlRightSide.setMinimumSize(new java.awt.Dimension(300, 55));
        pnlRightSide.setPreferredSize(new java.awt.Dimension(300, 55));
        java.awt.FlowLayout flowLayout1 = new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT, 0, 0);
        flowLayout1.setAlignOnBaseline(true);
        pnlRightSide.setLayout(flowLayout1);

        lblClock.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblClock.setForeground(new java.awt.Color(102, 102, 102));
        lblClock.setText("15:33:22");
        lblClock.setMaximumSize(new java.awt.Dimension(90, 15));
        lblClock.setMinimumSize(new java.awt.Dimension(90, 15));
        lblClock.setPreferredSize(new java.awt.Dimension(90, 15));
        pnlRightSide.add(lblClock);

        btnUserMenu.setBackground(new java.awt.Color(255, 255, 255));
        btnUserMenu.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnUserMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-user-28.png"))); // NOI18N
        btnUserMenu.setText("- User Name -");
        btnUserMenu.setBorderPainted(false);
        btnUserMenu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnUserMenu.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnUserMenu.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnUserMenu.setMaximumSize(new java.awt.Dimension(250, 55));
        btnUserMenu.setMinimumSize(new java.awt.Dimension(160, 55));
        btnUserMenu.setPreferredSize(new java.awt.Dimension(180, 55));
        btnUserMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnUserMenuMouseReleased(evt);
            }
        });
        pnlRightSide.add(btnUserMenu);

        add(pnlRightSide, new java.awt.GridBagConstraints());
    }// </editor-fold>//GEN-END:initComponents

    private void btnUserMenuMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUserMenuMouseReleased
        if (evt.getButton() == 1) { // 1-left, 2-middle, 3-right button
            popupUserMenu.show(evt.getComponent(), 0, evt.getComponent().getHeight() - 1);
        }
    }//GEN-LAST:event_btnUserMenuMouseReleased

    private void mnuAccountDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuAccountDetailsActionPerformed
        btnDashboard.setForeground(Color.BLACK);
        btnReports.setForeground(new Color(0, 120, 215));
        btnUsersManagement.setForeground(Color.BLACK);
        btnProductManagement.setForeground(Color.BLACK);
        ((EposSimpleApp) SwingUtilities.getWindowAncestor(this)).showReports();
    }//GEN-LAST:event_mnuAccountDetailsActionPerformed

    private void mnuLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuLogoutActionPerformed
        ((EposSimpleApp) SwingUtilities.getWindowAncestor(this)).logoutUser();
    }//GEN-LAST:event_mnuLogoutActionPerformed

    private void mnuExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuExitActionPerformed
        ((EposSimpleApp) SwingUtilities.getWindowAncestor(this)).exit();
    }//GEN-LAST:event_mnuExitActionPerformed

    private void btnDashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDashboardActionPerformed
        btnDashboard.setForeground(new Color(0, 120, 215));
        btnReports.setForeground(Color.BLACK);
        btnUsersManagement.setForeground(Color.BLACK);
        btnProductManagement.setForeground(Color.BLACK);
        ((EposSimpleApp) SwingUtilities.getWindowAncestor(this)).showDashboard();
    }//GEN-LAST:event_btnDashboardActionPerformed

    private void btnReportsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportsActionPerformed
        btnDashboard.setForeground(Color.BLACK);
        btnReports.setForeground(new Color(0, 120, 215));
        btnUsersManagement.setForeground(Color.BLACK);
        btnProductManagement.setForeground(Color.BLACK);
        ((EposSimpleApp) SwingUtilities.getWindowAncestor(this)).showReports();
    }//GEN-LAST:event_btnReportsActionPerformed

    private void btnUsersManagementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsersManagementActionPerformed
        btnDashboard.setForeground(Color.BLACK);
        btnReports.setForeground(Color.BLACK);
        btnUsersManagement.setForeground(new Color(0, 120, 215));
        btnProductManagement.setForeground(Color.BLACK);
        ((EposSimpleApp) SwingUtilities.getWindowAncestor(this)).showUserManagement();
    }//GEN-LAST:event_btnUsersManagementActionPerformed

    private void btnProductManagementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProductManagementActionPerformed
        btnDashboard.setForeground(Color.BLACK);
        btnReports.setForeground(Color.BLACK);
        btnUsersManagement.setForeground(Color.BLACK);
        btnProductManagement.setForeground(new Color(0, 120, 215));
        ((EposSimpleApp) SwingUtilities.getWindowAncestor(this)).showProductManagement();
    }//GEN-LAST:event_btnProductManagementActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDashboard;
    private javax.swing.JButton btnProductManagement;
    private javax.swing.JButton btnReports;
    private javax.swing.JButton btnUserMenu;
    private javax.swing.JButton btnUsersManagement;
    private javax.swing.JLabel lblClock;
    private javax.swing.JMenuItem mnuAccountDetails;
    private javax.swing.JMenuItem mnuExit;
    private javax.swing.JMenuItem mnuLogout;
    private javax.swing.JPanel pnlLeftSide;
    private javax.swing.JPanel pnlRightSide;
    private javax.swing.JPopupMenu popupUserMenu;
    private javax.swing.JSeparator sep1;
    private javax.swing.JSeparator sep2;
    private javax.swing.JSeparator sep3;
    // End of variables declaration//GEN-END:variables
}
