/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package EposSimple.Panels;

import EposSimple.EposSimpleApp;
import EposSimple.Helpers.*;
import EposSimple.Models.*;
import EposSimple.Widgets.UserListWidget;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.BorderFactory;

/**
 *
 * @author tg
 */
public class UserManagement extends javax.swing.JPanel {

    User loggedUser;
    EposSimpleApp parentFrame;
    ArrayList<Sale> sales;
    ArrayList<Report> reports;
    ArrayList<User> users;
    
    ArrayList<UserListWidget> userWidgets = new ArrayList<>();

    /**
     * Creates new form SalesDashboard
     *
     * @param parentFrame
     * @param loggedUser
     * @param sales
     */
    public UserManagement(EposSimpleApp parentFrame, User loggedUser, ArrayList<Sale> sales, ArrayList<User> users) {
        this.loggedUser = loggedUser;
        this.parentFrame = parentFrame;
        this.sales = sales;
        this.users = users;
        initComponents();
        
        reports = new ArrayList<>();
        
        for(User user : users){
            reports.add(new Report(sales, user));
        }
        
        for (int i = 0; i < reports.size(); i++) {
            userWidgets.add(new UserListWidget(parentFrame, this, reports.get(i)));
            pnlUsersList.add(userWidgets.get(i));
        }
        pnlUsersList.validate();
        pnlUsersList.repaint();

        DragScrollListener listener = new DragScrollListener(pnlUsersList);
        pnlUsersList.addMouseListener(listener);
        pnlUsersList.addMouseMotionListener(listener);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        srllPanel = new CustomScrollPane();
        pnlUsersList = new javax.swing.JPanel();
        pnlRightPanel = new javax.swing.JPanel();
        pnlAligningPane = new javax.swing.JPanel();
        pnlContent = new javax.swing.JPanel();
        lblSelectUserFromList = new javax.swing.JLabel();
        pnlUserReport = new javax.swing.JPanel();
        lblSelected = new javax.swing.JLabel();
        lblSelectedValue = new javax.swing.JLabel();
        lblTotalCustomers = new javax.swing.JLabel();
        lblTotalCustomersValue = new javax.swing.JLabel();
        lblTotalSales = new javax.swing.JLabel();
        lblTotalSalesValue = new javax.swing.JLabel();
        lblAverageSale = new javax.swing.JLabel();
        lblAverageSaleValue = new javax.swing.JLabel();
        lblMinimalSale = new javax.swing.JLabel();
        lblMinimalSaleValue = new javax.swing.JLabel();
        lblMaximumSale = new javax.swing.JLabel();
        lblMaximumSaleValue = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(BorderFactory.createMatteBorder(1, 0, 0, 0, Color.BLACK));
        setMaximumSize(new java.awt.Dimension(1260, 626));
        setMinimumSize(new java.awt.Dimension(1260, 626));
        setPreferredSize(new java.awt.Dimension(1260, 626));
        setLayout(new java.awt.GridBagLayout());

        srllPanel.setBackground(new java.awt.Color(255, 255, 255));
        srllPanel.setBorder(null);
        srllPanel.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        srllPanel.setPreferredSize(new java.awt.Dimension(314, 604));

        pnlUsersList.setBackground(new java.awt.Color(255, 255, 255));
        pnlUsersList.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        pnlUsersList.setLayout(new javax.swing.BoxLayout(pnlUsersList, javax.swing.BoxLayout.PAGE_AXIS));
        srllPanel.setViewportView(pnlUsersList);

        add(srllPanel, new java.awt.GridBagConstraints());

        pnlRightPanel.setBackground(new java.awt.Color(255, 255, 255));
        pnlRightPanel.setPreferredSize(new java.awt.Dimension(930, 604));
        pnlRightPanel.setLayout(new javax.swing.BoxLayout(pnlRightPanel, javax.swing.BoxLayout.PAGE_AXIS));

        pnlAligningPane.setLayout(new javax.swing.BoxLayout(pnlAligningPane, javax.swing.BoxLayout.LINE_AXIS));

        pnlContent.setBackground(new java.awt.Color(255, 255, 255));
        pnlContent.setLayout(new java.awt.GridBagLayout());

        lblSelectUserFromList.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblSelectUserFromList.setForeground(new java.awt.Color(204, 204, 204));
        lblSelectUserFromList.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSelectUserFromList.setText("Select User from the list on the left hand size.");
        lblSelectUserFromList.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 15));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        pnlContent.add(lblSelectUserFromList, gridBagConstraints);

        pnlUserReport.setBackground(new java.awt.Color(255, 255, 255));
        pnlUserReport.setLayout(new java.awt.GridBagLayout());

        lblSelected.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblSelected.setText("Selected User:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 10;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        pnlUserReport.add(lblSelected, gridBagConstraints);

        lblSelectedValue.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblSelectedValue.setText("User 1 Name");
        lblSelectedValue.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 15));
        lblSelectedValue.setMaximumSize(new java.awt.Dimension(200, 19));
        lblSelectedValue.setMinimumSize(new java.awt.Dimension(200, 19));
        lblSelectedValue.setPreferredSize(new java.awt.Dimension(200, 19));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        pnlUserReport.add(lblSelectedValue, gridBagConstraints);

        lblTotalCustomers.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblTotalCustomers.setText("Total customers served:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 10;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        pnlUserReport.add(lblTotalCustomers, gridBagConstraints);

        lblTotalCustomersValue.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblTotalCustomersValue.setText("153");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        pnlUserReport.add(lblTotalCustomersValue, gridBagConstraints);

        lblTotalSales.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblTotalSales.setText("Total sales value:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 3;
        gridBagConstraints.ipadx = 10;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        pnlUserReport.add(lblTotalSales, gridBagConstraints);

        lblTotalSalesValue.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblTotalSalesValue.setText("£3500.42");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        pnlUserReport.add(lblTotalSalesValue, gridBagConstraints);

        lblAverageSale.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblAverageSale.setText("Average sale value:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 4;
        gridBagConstraints.ipadx = 10;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        pnlUserReport.add(lblAverageSale, gridBagConstraints);

        lblAverageSaleValue.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblAverageSaleValue.setText("£45.22");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        pnlUserReport.add(lblAverageSaleValue, gridBagConstraints);

        lblMinimalSale.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblMinimalSale.setText("Minimal sale value:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 5;
        gridBagConstraints.ipadx = 10;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        pnlUserReport.add(lblMinimalSale, gridBagConstraints);

        lblMinimalSaleValue.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblMinimalSaleValue.setText("£3.45");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        pnlUserReport.add(lblMinimalSaleValue, gridBagConstraints);

        lblMaximumSale.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblMaximumSale.setText("Maximum sale value:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 6;
        gridBagConstraints.ipadx = 10;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        pnlUserReport.add(lblMaximumSale, gridBagConstraints);

        lblMaximumSaleValue.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblMaximumSaleValue.setText("£548.00");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        pnlUserReport.add(lblMaximumSaleValue, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        pnlContent.add(pnlUserReport, gridBagConstraints);
        pnlUserReport.setVisible(false);

        pnlAligningPane.add(pnlContent);

        pnlRightPanel.add(pnlAligningPane);

        add(pnlRightPanel, new java.awt.GridBagConstraints());
    }// </editor-fold>//GEN-END:initComponents

    public void selectUser(UserListWidget selectedWidget, Report selectedReport){
        for(UserListWidget widget : userWidgets){
            widget.deselect();
        }
        selectedWidget.select();
        
        String reportName = selectedReport.getUser().getLogin();
        lblSelectedValue.setText(reportName);
        
        double totalSalesValue = selectedReport.getTotalSalesValue();
        lblTotalSalesValue.setText("£" + String.format("%.2f", totalSalesValue));
        
        double totalCusotmersValue = selectedReport.getTotalCustomerServed();
        lblTotalCustomersValue.setText(String.format("%.0f", totalCusotmersValue));
        
        double averageSaleValue = selectedReport.getAvgSaleValue();
        lblAverageSaleValue.setText("£" + String.format("%.2f", averageSaleValue));
        
        double minimalSaleValue = selectedReport.getMinSaleValue();
        lblMinimalSaleValue.setText("£" + String.format("%.2f", minimalSaleValue));
        
        double maximumSaleValue = selectedReport.getMaxSaleValue();
        lblMaximumSaleValue.setText("£" + String.format("%.2f", maximumSaleValue));
        
        
        lblSelectUserFromList.setVisible(false);
        pnlUserReport.setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblAverageSale;
    private javax.swing.JLabel lblAverageSaleValue;
    private javax.swing.JLabel lblMaximumSale;
    private javax.swing.JLabel lblMaximumSaleValue;
    private javax.swing.JLabel lblMinimalSale;
    private javax.swing.JLabel lblMinimalSaleValue;
    private javax.swing.JLabel lblSelectUserFromList;
    private javax.swing.JLabel lblSelected;
    private javax.swing.JLabel lblSelectedValue;
    private javax.swing.JLabel lblTotalCustomers;
    private javax.swing.JLabel lblTotalCustomersValue;
    private javax.swing.JLabel lblTotalSales;
    private javax.swing.JLabel lblTotalSalesValue;
    private javax.swing.JPanel pnlAligningPane;
    private javax.swing.JPanel pnlContent;
    private javax.swing.JPanel pnlRightPanel;
    private javax.swing.JPanel pnlUserReport;
    private javax.swing.JPanel pnlUsersList;
    private javax.swing.JScrollPane srllPanel;
    // End of variables declaration//GEN-END:variables

    private void updateShownReport(Report selectedReport) {
        String reportName = selectedReport.getReportName();
        lblSelectedValue.setText(reportName);
        
        double totalSalesValue = selectedReport.getTotalSalesValue();
        lblTotalSalesValue.setText("£" + String.format("%.2f", totalSalesValue));
        
        double totalCusotmersValue = selectedReport.getTotalCustomerServed();
        lblTotalCustomersValue.setText(String.format("%.0f", totalCusotmersValue));
        
        double averageSaleValue = selectedReport.getAvgSaleValue();
        lblAverageSaleValue.setText("£" + String.format("%.2f", averageSaleValue));
        
        double minimalSaleValue = selectedReport.getMinSaleValue();
        lblMinimalSaleValue.setText("£" + String.format("%.2f", minimalSaleValue));
        
        double maximumSaleValue = selectedReport.getMaxSaleValue();
        lblMaximumSaleValue.setText("£" + String.format("%.2f", maximumSaleValue));

    }

}
